#!/usr/bin/env node
// Bounded companion assets. No server, production state or account access.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
const root = new URL('../../',import.meta.url)
const read = p => readFileSync(new URL(p,root),'utf8')
const roster = JSON.parse(read('daemons/roster.json'))
const plates = JSON.parse(read('daemons/plates.json'))
const tim = roster.daemons.find(d=>d.id==='tim')
const assets = {tim,plate:roster.rules.plate,eggs:plates.eggs,eggKinds:roster.rules.eggs}
const outputs = {
  'cli/src/cable/timPerformance.g.ts': '// Generated by daemons/companion/generate.mjs.\n// @ts-nocheck\n'+read('daemons/companion/tim.mjs'),
  'cli/src/cable/companionArtwork.g.ts': '// Generated by daemons/companion/generate.mjs.\nexport const COMPANION_ARTWORK = '+JSON.stringify(assets)+'\n',
}
for(const [name,content] of Object.entries(outputs)) {
  if(process.argv.includes('--check')) {
    if(read(name)!==content)throw new Error(`${name} is stale`)
  } else writeFileSync(fileURLToPath(new URL(name,root)),content)
}
