// Generated by daemons/companion/generate.mjs.
// @ts-nocheck
// Tim's small stage. One deterministic rig supplies the desktop and USB clips.
// The seed/traits are the existing account individual's; animation never rolls them.
export const EMOTIONS = ['content', 'curious', 'bored', 'playful', 'working', 'focused',
  'happy', 'excited', 'proud', 'relieved', 'frustrated', 'angry', 'sad', 'tired',
  'exhausted', 'attentive', 'asleep', 'offline', 'listening', 'affectionate', 'hatching']

// Eight poses include anticipation, action and a soft landing. Quiet uses pose 0.
const jump = [0, -1, 2, 5, 3, 0, 2, 0]
const wave = [0, .7, 1, .7, 0, -.7, -1, -.7]
export function timFrame(traits, age, emotion = 'content', frame = 0, cols = 56) {
  const T = traits
  const rows = Math.round(cols * 30 / 56), scale = cols / 56
  const ink = Array.from({length: rows}, () => Array(cols).fill(' '))
  const mats = Array.from({length: rows}, () => Array(cols).fill('.'))
  const depth = Array.from({length: rows}, () => Array(cols).fill(-1))
  const put = (x, y, ch, mat = '.', z = 9) => {
    x = Math.round(x * scale); y = Math.round(y * scale)
    if (x >= 0 && x < cols && y >= 0 && y < rows && z >= depth[y][x]) {
      ink[y][x] = ch; mats[y][x] = mat; depth[y][x] = z
    }
  }
  const f = frame % 8, t = f * Math.PI / 4
  const baby = age === '0.1', young = age === '1.0'
  const s = baby ? .62 : young ? .82 : 1
  const joy = ['excited', 'happy', 'hatching'].includes(emotion)
  const low = ['sad', 'tired', 'exhausted', 'asleep', 'offline'].includes(emotion)
  const angry = ['angry', 'frustrated'].includes(emotion)
  const active = ['working', 'focused', 'playful', 'listening'].includes(emotion)
  const bob = joy ? jump[f] * (emotion === 'excited' ? 1 : .55)
    : emotion === 'playful' ? Math.abs(wave[f]) * 2 : 0
  const cx = 27.5 + (angry ? wave[f] * 1.1 : emotion === 'curious' ? wave[f] * .7 : 0)
  const cy = 23 - s * 8 - bob + (low ? 1.2 : 0)
  const squash = emotion === 'exhausted' ? .75 : emotion === 'tired' ? .88 : joy && f === 1 ? .88 : joy && f === 3 ? 1.06 : 1
  const rx = 12 * s * T.head / squash
  const ry = (baby ? 5.9 : 6.6) * s * T.head * squash
  // A shaded ellipse, sampled at terminal-cell centers. Overlapping ellipses
  // join tentacles smoothly; material masks stay attached to the same body.
  const blob = (x, y, a, b, z, material = '.', marking = false) => {
    for (let py = Math.max(0, Math.floor((y-b)*scale)); py <= Math.min(rows-1, Math.ceil((y+b)*scale)); py++) {
      for (let px = Math.max(0, Math.floor((x-a)*scale)); px <= Math.min(cols-1, Math.ceil((x+a)*scale)); px++) {
        const dx = (px/scale-x)/a, dy = (py/scale-y)/b, d = dx*dx+dy*dy
        if (d > 1 || z < depth[py][px]) continue
        const shade = Math.max(0, Math.min(5, Math.floor((1-d)*3 + (1-dx)*1.3)))
        let mat = material
        if (marking) {
          if (T.marks === 'spots' && Math.sin(dx*5+T.seed%7)*Math.cos(dy*4)>.64) mat='m'
          if (T.marks === 'patches' && ((dx+.5)**2+(dy+.3)**2<.22 || (dx-.6)**2+(dy-.15)**2<.13)) mat='m'
        }
        ink[py][px] = ',:ox%#'[shade]; mats[py][px]=mat; depth[py][px]=z
      }
    }
  }
  // Four separate arms on each side. The outer pair performs; the others
  // balance, curl, tap, or tuck underneath him, with individual arm/curl traits.
  for (const side of [-1, 1]) for (let arm = 0; arm < 4; arm++) {
    const x0 = cx + side * (8-arm*2.15) * s
    const y0 = cy + ry*.68 + arm*.5*s
    const span = (baby ? 6.8 : 12.5) * s * T.arms * (1-arm*.2)
    const raised = joy || emotion === 'proud' || emotion === 'attentive' || emotion === 'affectionate'
    const reach = arm === 0 ? (raised ? -5.5 : emotion === 'curious' && side>0 ? -2.5 : 2.6) : 3.2 + arm*.65
    for (let step = 0; step <= 44; step++) {
      const u = step/44, curl = Math.max(0,(u-.6)/.4)*Math.PI*1.7*T.curl
      const wiggle = Math.sin(t*(T.temper==='fidgety'?2:1)+arm*1.3+side)*u
      const x = x0 + side*(span*u + Math.sin(curl)*2.1*s*u)
      const y = y0 + (reach*u + Math.cos(curl)*1.4*u + wiggle*(active?1.5:.45))*s + (low?1.2*u:0)
      const mat = T.marks==='stripes' && Math.floor(u*7)%2 ? 'm' : '.'
      blob(x,y,(2.2-1.5*u)*s,(1.15-.72*u)*s,arm+1,mat)
    }
  }
  blob(cx,cy,rx,ry,6,'.',true)
  blob(cx,cy+ry*.58,rx*.72,ry*.56,6,'.',true)
  const eyeY = cy + ry*.3, gap = 4.3*s*T.gap
  const eyes = low ? (emotion==='asleep' ? '---' : '-o-')
    : angry ? (emotion==='angry' ? '\\ /' : '> <')
    : joy || ['proud','relieved','affectionate'].includes(emotion) ? '^ ^'
    : emotion==='attentive' ? 'O O' : '@ @'
  for (const side of [-1,1]) {
    const x = cx+side*gap, er = Math.max(1.8,2.5*s*T.eyes)
    blob(x,eyeY,er,1.65*s,7)
    // Clear eye sockets in the same silhouette; lids blink at one quiet beat.
    for(let yy=-1; yy<=1; yy++) for(let xx=-1; xx<=1; xx++) put(x+xx,eyeY+yy*s,' ','.',8)
    let ch = side<0 ? eyes[0] : eyes[2]
    if (f===7 && !joy && !angry && emotion!=='listening') ch='-'
    if (emotion==='curious') ch=side>0?'O':'o'
    if (emotion==='focused') ch=side<0?'>':'<'
    const mat = T.oddEye && side>0 ? 'e' : 'p'
    put(x+(emotion==='bored' ? wave[f] : 0),eyeY,ch,mat)
    if(!low && !angry && !joy && f!==7) {put(x-1,eyeY,'(',mat);put(x+1,eyeY,')',mat)}
    if(T.marks==='freckles') for(let k=0;k<2;k++) put(x+side*(2+k),eyeY+1.8*s,'.','m')
  }
  const mouthY=eyeY+2.5*s
  const mouth = emotion==='listening' ? ['.','o','O','o'][f%4]
    : joy ? 'U' : emotion==='affectionate' ? 'w' : low ? '_' : angry ? '~' : emotion==='relieved' ? 'u' : '.'
  put(cx,mouthY,mouth)
  // The account's accessories persist at every age, mood and orientation.
  if(T.extra==='glasses') for(const side of [-1,1]) {
    const x=cx+side*gap
    put(x-2,eyeY,'(','a');put(x+2,eyeY,')','a');put(cx,eyeY,'-','a')
  }
  if(T.extra==='beanie') {
    blob(cx,cy-ry*.75,rx*.92,1.3*s,10,'a')
    blob(cx,cy-ry-1*s,rx*.65,1.7*s,10,'a')
    blob(cx+wave[f]*s,cy-ry-2.4*s,1.3*s,.7*s,10,'a')
  }
  if(T.extra==='headset') {
    for(let i=0;i<=30;i++) { const a=Math.PI+i*Math.PI/30;put(cx+Math.cos(a)*(rx+.7),cy+Math.sin(a)*(ry+.8),'#','a') }
    for(const side of [-1,1]) blob(cx+side*rx,eyeY,1.2*s,1.7*s,10,'a')
    put(cx+rx*.8,eyeY+2,'o','a')
  }
  if(emotion==='asleep') {put(cx+rx+3,cy-2,'z'); if(f>3)put(cx+rx+5,cy-4,'z')}
  if(emotion==='excited' && f>=2 && f<=5) for(const side of [-1,1]) {put(cx+side*(rx+5),cy-3,'+','m');put(cx+side*(rx+7),cy,'*','m')}
  if(emotion==='affectionate' && f>=2 && f<=5) {put(cx+rx+4,cy-2,'<','m');put(cx+rx+5,cy-2,'3','m')}
  if(emotion==='playful') {put(cx+Math.cos(t)*rx,cy-ry-2,'*','m')}
  if(emotion==='sad' && f>3) {put(cx+gap+1,eyeY+2+(f-4)*.5,'o','e')}
  if(emotion==='frustrated' || emotion==='angry') put(cx+rx+3,cy-ry/2,f%2?'!':'~','m')
  return {rows:ink.map(r=>r.join('')).join('\n'),mats:mats.map(r=>r.join('')).join('\n')}
}

export function timClip(traits, age, emotion, cols = 56) {
  return Array.from({length:8}, (_,f)=>timFrame(traits,age,emotion,f,cols))
}
